import { google } from "googleapis";
import nodemailer from "nodemailer";
import { NextRequest, NextResponse } from "next/server";

export const runtime = "nodejs";
type OrderInput={name:string;phone:string;email:string;location:string;productName:string;quantity:number;pricePerPiece:number;totalPrice:number;packageName?:string};
const required=["GOOGLE_SHEET_ID","GOOGLE_SHEET_TAB_NAME","GOOGLE_SERVICE_ACCOUNT_EMAIL","GOOGLE_PRIVATE_KEY","BUSINESS_EMAIL","EMAIL_FROM","SMTP_HOST","SMTP_PORT","SMTP_USER","SMTP_PASS"] as const;
const packTotals: Record<number, number> = { 1: 699, 2: 1299, 3: 1799, 4: 2299 };
const headers=["Order ID","Date & Time","Customer Name","Phone Number","Email Address","Exact Location","Product Name","Quantity","Price Per Piece","Total Price","Payment Method","Order Status","Notes"];
function valid(input:OrderInput) { return input.name?.trim()&&input.phone?.trim()&&/^\S+@\S+\.\S+$/.test(input.email||"")&&input.location?.trim()&&input.productName?.trim()&&Number.isInteger(input.quantity)&&input.quantity>=1&&Number.isFinite(input.pricePerPiece)&&input.pricePerPiece>0&&Number.isFinite(input.totalPrice)&&input.totalPrice>0; }
function money(v:number){return `Rs. ${v.toLocaleString("en-IN")}`;}
function html(title:string, body:string) { return `<div style="margin:0;padding:32px 12px;background:#f8f2e9;font-family:Arial,sans-serif;color:#22140f"><table role="presentation" style="max-width:620px;width:100%;margin:auto;background:#fff;border-radius:20px;overflow:hidden;border-collapse:separate"><tr><td style="background:#22140f;padding:28px 34px;color:#f4d59f"><span style="font-size:25px;font-weight:bold;letter-spacing:4px">☕ NEP</span><br><span style="font-size:11px;letter-spacing:2px">NEPALI COFFEE COMPANY</span></td></tr><tr><td style="padding:34px">${body}</td></tr><tr><td style="padding:22px 34px;background:#f4ecdf;font-size:12px;color:#6c5140">${title} · Premium coffee, proudly Nepali</td></tr></table></div>`; }
function rows(o:OrderInput,id:string,date:string) { return `<table role="presentation" style="width:100%;border-collapse:collapse;font-size:14px">${[["Order ID",id],["Date & time",date],["Customer",o.name],["Phone",o.phone],["Email",o.email],["Location",o.location],["Product",o.packageName||o.productName],["Price per piece",money(o.pricePerPiece)],["Total",money(o.totalPrice)],["Payment","Cash On Delivery"],["Status","New Order"]].map(([k,v])=>`<tr><td style="padding:10px 0;border-bottom:1px solid #eadfce;color:#755943">${k}</td><td style="padding:10px 0;border-bottom:1px solid #eadfce;text-align:right;font-weight:600">${v}</td></tr>`).join("")}</table>`; }
async function prepareOrderSheet(sheets: ReturnType<typeof google.sheets>) { const tab=process.env.GOOGLE_SHEET_TAB_NAME!; const book=await sheets.spreadsheets.get({spreadsheetId:process.env.GOOGLE_SHEET_ID,fields:"sheets(properties(sheetId,title))"}); let sheet=book.data.sheets?.find(s=>s.properties?.title===tab); if(sheet?.properties?.sheetId===undefined) { const created=await sheets.spreadsheets.batchUpdate({spreadsheetId:process.env.GOOGLE_SHEET_ID,requestBody:{requests:[{addSheet:{properties:{title:tab}}}]}}); sheet=created.data.replies?.[0]?.addSheet; } if(sheet?.properties?.sheetId===undefined) throw new Error(`Unable to create Google Sheet tab "${tab}".`); const firstRow=await sheets.spreadsheets.values.get({spreadsheetId:process.env.GOOGLE_SHEET_ID,range:`${tab}!A1:M1`}); if(!firstRow.data.values?.[0]?.length) await sheets.spreadsheets.values.update({spreadsheetId:process.env.GOOGLE_SHEET_ID,range:`${tab}!A1:M1`,valueInputOption:"RAW",requestBody:{values:[headers]}}); const sheetId=sheet.properties.sheetId; await sheets.spreadsheets.batchUpdate({spreadsheetId:process.env.GOOGLE_SHEET_ID,requestBody:{requests:[{updateSheetProperties:{properties:{sheetId,gridProperties:{frozenRowCount:1}},fields:"gridProperties.frozenRowCount"}},{repeatCell:{range:{sheetId,startRowIndex:0,endRowIndex:1,startColumnIndex:0,endColumnIndex:13},cell:{userEnteredFormat:{backgroundColor:{red:0.13,green:0.08,blue:0.06},textFormat:{foregroundColor:{red:1,green:0.9,blue:0.72},bold:true},horizontalAlignment:"CENTER",verticalAlignment:"MIDDLE",wrapStrategy:"WRAP"}},fields:"userEnteredFormat(backgroundColor,textFormat,horizontalAlignment,verticalAlignment,wrapStrategy)"}},{setBasicFilter:{filter:{range:{sheetId,startRowIndex:0,startColumnIndex:0,endColumnIndex:13}}}},{autoResizeDimensions:{dimensions:{sheetId,dimension:"COLUMNS",startIndex:0,endIndex:13}}}]}}); }
export async function OPTIONS() { return new NextResponse(null,{status:204,headers:{"Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type"}}); }
export async function POST(req:NextRequest) { try { const origin=req.headers.get("origin"); if(process.env.FRONTEND_URL&&origin&&origin!==process.env.FRONTEND_URL) return NextResponse.json({error:"Unauthorized origin."},{status:403}); const submitted=await req.json() as OrderInput; const total=packTotals[submitted.quantity]; const data: OrderInput = total ? {...submitted, productName:"Nep Coffee", pricePerPiece:Math.round(total/submitted.quantity), totalPrice:total} : submitted; if(!valid(data)||!total) return NextResponse.json({error:"Please provide valid name, phone, email, location, product and price details."},{status:400}); const missing=required.filter(k=>!process.env[k]); if(missing.length) { console.error("Missing server configuration:",missing); return NextResponse.json({error:"Ordering is not configured yet. Please contact us by phone."},{status:503}); }
  const orderId=`NEP-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`; const date=new Intl.DateTimeFormat("en-NP",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Kathmandu"}).format(new Date());
  const auth=new google.auth.JWT({email:process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key:process.env.GOOGLE_PRIVATE_KEY!.replace(/\\n/g,"\n"),scopes:["https://www.googleapis.com/auth/spreadsheets"]}); const sheets=google.sheets({version:"v4",auth}); await prepareOrderSheet(sheets); await sheets.spreadsheets.values.append({spreadsheetId:process.env.GOOGLE_SHEET_ID,range:`${process.env.GOOGLE_SHEET_TAB_NAME}!A:M`,valueInputOption:"USER_ENTERED",requestBody:{values:[[orderId,date,data.name.trim(),data.phone.trim(),data.email.trim(),data.location.trim(),data.packageName||data.productName,data.quantity,data.pricePerPiece,data.totalPrice,"Cash On Delivery","New Order",""]]}});
  const transporter=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT),secure:Number(process.env.SMTP_PORT)===465,auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}}); const brand=process.env.BRAND_NAME||"Nep Coffee"; await transporter.sendMail({from:process.env.EMAIL_FROM,to:process.env.BUSINESS_EMAIL,replyTo:data.email,subject:`New Product Order Received - ${orderId}`,html:html(brand,`<h1 style="margin:0 0 10px;font-size:26px">New order received</h1><p style="color:#755943;line-height:1.6">A customer has placed a cash-on-delivery order.</p>${rows(data,orderId,date)}<p style="margin:24px 0 0;padding:14px 16px;background:#fff1d8;border-radius:10px;font-weight:bold">Please call the customer soon to confirm this order.</p>`)}); await transporter.sendMail({from:process.env.EMAIL_FROM,to:data.email,replyTo:process.env.EMAIL_FROM,subject:`Your Order Has Been Received - ${brand}`,html:html(brand,`<h1 style="margin:0 0 12px;font-size:26px">Thank you, ${data.name}!</h1><p style="line-height:1.7;color:#5d4030">We have received your order successfully. Our sales representative will call you soon to confirm your order.</p>${rows(data,orderId,date)}<p style="margin:24px 0 0;line-height:1.6;color:#5d4030">Thank you for choosing ${brand}. If you need help, reply to this email.</p>`)}); return NextResponse.json({success:true,orderId});
 } catch(error) { console.error("Order submission failed:",error); return NextResponse.json({error:"We could not submit your order. Please try again or call 9861676300."},{status:500}); } }
